services:
  postgres:
    image: postgres:16
    container_name: jobstories-postgres
    environment:
      POSTGRES_DB: jobstories
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  story-service:
    build:
      context: ./story-service
    container_name: story-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobstories
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
